add reStartRecordingLive function
argmaxinc/WhisperKit pull request #138
Opened 2024-05-14 11:50 UTC by fengcunhan

You can continues record after pause recording

2024-05-14 13:36 UTC, ZachNagengast requested changes
This is great, seems like there was the pause feature but was missing resume, suggested a couple changes for clarity.

2024-05-14 13:36 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +        // Set the callback
```suggestion

        // Set the callback
```

2024-05-14 13:36 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +    func reStartRecordingLive(inputDeviceID: DeviceID? = nil, callback: (([Float]) -> Void)? = nil) throws {
```suggestion
    func resumeRecordingLive(inputDeviceID: DeviceID? = nil, callback: (([Float]) -> Void)? = nil) throws {
```

2024-05-14 13:36 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +    }
```suggestion
    func resumeRecordingLive(inputDeviceID: DeviceID? = nil, callback: (([Float]) -> Void)?) throws {
        try resumeRecordingLive(inputDeviceID: inputDeviceID, callback: callback)
    }
```

2024-05-14 13:36 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +    func reStartRecordingLive(inputDeviceID: DeviceID?, callback: (([Float]) -> Void)?) throws
```suggestion
    /// Resume recording audio from the specified input device, appending to continuous `audioArray` after pause
    func resumeRecordingLive(inputDeviceID: DeviceID?, callback: (([Float]) -> Void)?) throws
```

2024-05-14 13:36 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +        }else{
```suggestion
        } else {
```

2024-05-14 14:39 UTC, fengcunhan commented on Sources/WhisperKit/Core/AudioProcessor.swift
> +        }else{
OK ，I will fix it

2024-05-14 14:47 UTC, fengcunhan commented
> This is great, seems like there was the pause feature but was missing resume, suggested a couple changes for clarity.

Yes,i will use your suggestion.Thank you for review my code.

2024-05-14 20:37 UTC, ZachNagengast commented on Sources/WhisperKit/Core/AudioProcessor.swift
>          audioBufferCallback = callback
Looking at it again, we probably won't want this to be overwritten when resuming if callback is nil and audioBufferCallback isn't nil

```suggestion
        // Set the callback only if the provided callback is not nil
        if let callback = callback {
            audioBufferCallback = callback
        }
```

2024-05-15 21:20 UTC, ZachNagengast approved these changes
Looks great! Thanks for contributing this @fengcunhan

2024-05-15 23:17 UTC, merged

2024-05-16 01:59 UTC, fengcunhan commented
> Looks great! Thanks for contributing this @fengcunhan

You are welcome.Thanks for  your patient of review my begainer level swift code.This project is awesome,i like it