Added implementation for SuppressTokensFilter
argmaxinc/WhisperKit pull request #14
Opened 2024-02-04 20:47 UTC by jkrukowski

- added implementation for SuppressTokensFilter
- added tests

If this PR looks good, I can try to implement other filters 🫡

2024-02-04 21:04 UTC, ZachNagengast commented
Awesome contribution! Reviewing this shortly

2024-02-04 23:18 UTC, ZachNagengast requested changes
This looks great @jkrukowski just a couple small notes, will run through the full tests as well.

2024-02-04 23:18 UTC, ZachNagengast commented on Tests/WhisperKitTests/UnitTests.swift
> +
Nice 👍

2024-02-05 17:15 UTC, ZachNagengast approved these changes
Updates look good, everything is passing, well done!

2024-02-05 17:28 UTC, ZachNagengast commented
Would love to see your take on the other filters if you're up for it! I'm going to be looking at word-level timestamps next on my side FYI, so we'll definitely need timestamp filtering i.e. [`ApplyTimestampRules`](https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/whisper/decoding.py#L441) equivalent for us, but keep in mind some of this logic we pulled into the `SegmentSeeking` protocol.

2024-02-05 17:38 UTC, jkrukowski commented
> Would love to see your take on the other filters if you're up for it! I'm going to be looking at word-level timestamps next on my side FYI, so we'll definitely need timestamp filtering i.e. [`ApplyTimestampRules`](https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/whisper/decoding.py#L441) equivalent for us, but keep in mind some of this logic we pulled into the `SegmentSeeking` protocol.

sure, happy to do it. Will try to find some time this or next week

2024-02-05 18:44 UTC, merged

2024-02-12 09:30 UTC, jkrukowski commented
> Would love to see your take on the other filters if you're up for it! I'm going to be looking at word-level timestamps next on my side FYI, so we'll definitely need timestamp filtering i.e. [`ApplyTimestampRules`](https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/whisper/decoding.py#L441) equivalent for us, but keep in mind some of this logic we pulled into the `SegmentSeeking` protocol.

hi @ZachNagengast, not sure if it's a good place to ask but you mentioned that some of this logic was pulled into `SegmentSeeking` protocol. Can you please elaborate a bit more?